/* ============================================
   THEME DEFINITIONS - 15 Color Themes
   ============================================ */

export const themes = [
  {
    name: "Material Teal",
    primary: "#05505E",
    primaryLight: "#0a7a8a",
    secondary: "#07beb8",
    accent: "#a1dded",
    bgPrimary: "#ffffff",
    bgSecondary: "#f8fffe",
    bgTertiary: "#e6faf5",
    textPrimary: "#05505E",
    textSecondary: "#528190",
    textMuted: "#6b9aa8",
    gradientStart: "#05505E",
    gradientEnd: "#07beb8",
  },
  {
    name: "Blue",
    primary: "#0E6BA8",
    primaryLight: "#1a8fd4",
    secondary: "#A6E1FA",
    accent: "#001C55",
    bgPrimary: "#EDF9FE",
    bgSecondary: "#ffffff",
    bgTertiary: "#d4f1fc",
    textPrimary: "#001C55",
    textSecondary: "#0A2472",
    textMuted: "#7F8DAA",
    gradientStart: "#0E6BA8",
    gradientEnd: "#0A2472",
  },
  {
    name: "Brown",
    primary: "#E29F95",
    primaryLight: "#f0b8b0",
    secondary: "#FB6376",
    accent: "#FFF9EC",
    bgPrimary: "#FFFEFD",
    bgSecondary: "#ffffff",
    bgTertiary: "#fff5f2",
    textPrimary: "#5D2A42",
    textSecondary: "#8D697A",
    textMuted: "#a88999",
    gradientStart: "#E29F95",
    gradientEnd: "#FB6376",
  },
  {
    name: "Purple",
    primary: "#BE95C4",
    primaryLight: "#d4b3d8",
    secondary: "#5E548E",
    accent: "#E0B1CB",
    bgPrimary: "#F8EFF4",
    bgSecondary: "#ffffff",
    bgTertiary: "#f0e4ec",
    textPrimary: "#231942",
    textSecondary: "#5E548E",
    textMuted: "#655E7A",
    gradientStart: "#BE95C4",
    gradientEnd: "#5E548E",
  },
  {
    name: "Green",
    primary: "#55a630",
    primaryLight: "#6cc244",
    secondary: "#007f5f",
    accent: "#dddf00",
    bgPrimary: "#FFFFEB",
    bgSecondary: "#ffffff",
    bgTertiary: "#f5f7e0",
    textPrimary: "#003F2F",
    textSecondary: "#007f5f",
    textMuted: "#4CA58F",
    gradientStart: "#55a630",
    gradientEnd: "#007f5f",
  },
  {
    name: "Red",
    primary: "#dc2f02",
    primaryLight: "#f04419",
    secondary: "#9d0208",
    accent: "#ffba08",
    bgPrimary: "#FFF8E6",
    bgSecondary: "#ffffff",
    bgTertiary: "#ffefcc",
    textPrimary: "#6a040f",
    textSecondary: "#9d0208",
    textMuted: "#964F56",
    gradientStart: "#dc2f02",
    gradientEnd: "#9d0208",
  },
  {
    name: "Black",
    primary: "#fca311",
    primaryLight: "#ffb733",
    secondary: "#14213d",
    accent: "#ffffff",
    bgPrimary: "#E5E5E5",
    bgSecondary: "#ffffff",
    bgTertiary: "#d4d4d4",
    textPrimary: "#14213d",
    textSecondary: "#000000",
    textMuted: "#5A6377",
    gradientStart: "#fca311",
    gradientEnd: "#14213d",
  },
  {
    name: "Pink",
    primary: "#ef476f",
    primaryLight: "#f76b8a",
    secondary: "#620E34",
    accent: "#FBA7CD",
    bgPrimary: "#FEE9F2",
    bgSecondary: "#ffffff",
    bgTertiary: "#fdd5e5",
    textPrimary: "#620E34",
    textSecondary: "#8a1548",
    textMuted: "#c45a7a",
    gradientStart: "#ef476f",
    gradientEnd: "#620E34",
  },
  {
    name: "Violet",
    primary: "#9b5de5",
    primaryLight: "#b07eec",
    secondary: "#763D8B",
    accent: "#D6BEF4",
    bgPrimary: "#F4EEFC",
    bgSecondary: "#ffffff",
    bgTertiary: "#e8ddf7",
    textPrimary: "#430A58",
    textSecondary: "#763D8B",
    textMuted: "#875599",
    gradientStart: "#9b5de5",
    gradientEnd: "#763D8B",
  },
  {
    name: "Teal",
    primary: "#07beb8",
    primaryLight: "#20d9d2",
    secondary: "#56a3a6",
    accent: "#9BEED8",
    bgPrimary: "#E6FAF5",
    bgSecondary: "#ffffff",
    bgTertiary: "#ccf5eb",
    textPrimary: "#084c61",
    textSecondary: "#0a6c7a",
    textMuted: "#528190",
    gradientStart: "#07beb8",
    gradientEnd: "#084c61",
  },
  {
    name: "Orange",
    primary: "#FF6B35",
    primaryLight: "#ff8555",
    secondary: "#d7263d",
    accent: "#FFB59A",
    bgPrimary: "#FFF0EA",
    bgSecondary: "#ffffff",
    bgTertiary: "#ffe0d4",
    textPrimary: "#99401F",
    textSecondary: "#CC552A",
    textMuted: "#c06040",
    gradientStart: "#FF6B35",
    gradientEnd: "#d7263d",
  },
  {
    name: "Yellow",
    primary: "#ffea3d",
    primaryLight: "#fff066",
    secondary: "#4e342e",
    accent: "#ffff73",
    bgPrimary: "#FFD95D",
    bgSecondary: "#ffe588",
    bgTertiary: "#ffcc33",
    textPrimary: "#5f4339",
    textSecondary: "#4e342e",
    textMuted: "#8d6e63",
    gradientStart: "#ffea3d",
    gradientEnd: "#ff9800",
  },
  {
    name: "Material Dark",
    primary: "#607d8b",
    primaryLight: "#78909c",
    secondary: "#8eacbb",
    accent: "#4f5b62",
    bgPrimary: "#263238",
    bgSecondary: "#37474f",
    bgTertiary: "#455a64",
    textPrimary: "#eceff1",
    textSecondary: "#b0bec5",
    textMuted: "#78909c",
    gradientStart: "#607d8b",
    gradientEnd: "#37474f",
  },
  {
    name: "Material Light",
    primary: "#7d56c2",
    primaryLight: "#9575cd",
    secondary: "#4c2b91",
    accent: "#E9E3F5",
    bgPrimary: "#ffffff",
    bgSecondary: "#fafafa",
    bgTertiary: "#f3f0f9",
    textPrimary: "#4c2b91",
    textSecondary: "#7d56c2",
    textMuted: "#9575cd",
    gradientStart: "#7d56c2",
    gradientEnd: "#4c2b91",
  },
  {
    name: "Indigo Purple",
    primary: "#667eea",
    primaryLight: "#7c8ff8",
    secondary: "#764ba2",
    accent: "#f093fb",
    bgPrimary: "#fafbfc",
    bgSecondary: "#ffffff",
    bgTertiary: "#f0f2f5",
    textPrimary: "#1a1a2e",
    textSecondary: "#4a5568",
    textMuted: "#718096",
    gradientStart: "#667eea",
    gradientEnd: "#764ba2",
  },
];

// Get a random theme
export const getRandomTheme = () => {
  const randomIndex = Math.floor(Math.random() * themes.length);
  return themes[randomIndex];
};

// Get theme by name
export const getThemeByName = (name) => {
  return themes.find(theme => theme.name === name) || themes[0];
};

export default themes;


